### ISSUE TITLE
"Generate Cards" Functionality / Page

### ISSUE THREAD

**Issue by DallasLaComb** [DallasLaComb/Flag-Bingo-Project#4]
"**[High priority] (13)** As the host I want to generate and print bingo cards so that I can have cards to play bingo."

Stan recommended for this that we create an HTML / Bootstrap type page for creating the page layout for this. So you would start with a 5*5 grid, where we add an algorithm to automatically create unique cards. 

(May not be 100% necessary, but shouldn't be hard to add, and with Dr.Mahoney saying that the amount of cards needing to be printed, that it would be a nice feature): A user input box that says "How many cards do you want to generate"

I think that we also came up with a rule that you need minimum (40?) flags for this to be effective: So making it known on the website that you need minimum 40 flags selected to save a lobby, which inertly also means you need minimum 40 flags to generate cards. 

I think this is a decent algorithm for generating the Flags, if someone comes up with something better we can look over that as well... : 

[\[02\]Hypothetical Game - Visual Shifting Algorithm - Sheet1.pdf](https://github.com/DallasLaComb/Flag-Bingo-Project/files/13062061/02.Hypothetical.Game.-.Visual.Shifting.Algorithm.-.Sheet1.pdf)

Possibly look into if there is a jQuery button to pull up the "Print Screen" console when click, to add simplicty to a set of non-technical users. If not possible, stan says it's ok to direct them on how to go to the print screen them semselves.

**Comment by DallasLaComb** [comment]
To format an HTML page to match the dimensions of standard printing paper (either A4 or 8.5x11 inches), various CSS properties and media queries can be utilized. Here are a few methods based on different sources:

1. **A4 Paper Size:**
   - Utilize the `@page` directive to specify the size of the page when printed. You would set the `size` property to `21cm 29.7cm` which corresponds to the dimensions of A4 paper. Additionally, you can set the `margin` property to adjust the margins to your liking【6†(source)】.
   ```css
   @page {
     size: 21cm 29.7cm;
     margin: 30mm 45mm 30mm 45mm; /* Change the margins as you want them to be. */
   }
   ```
   - Another method is to employ a print media query to set the width and height of the `html` and `body` elements to the dimensions of A4 paper. In the following snippet, the dimensions are set to `210mm` and `297mm`, respectively, which correspond to the dimensions of A4 paper【6†(source)】.
   ```css
   @media print {
     html, body {
       width: 210mm;
       height: 297mm;
     }
   }
   @page {
     size: A4;
     margin: 0;
   }
   ```

2. **8.5x11 Inch Paper Size:**
   - For an 8.5x11 inch paper size, you can specify the width and padding of the `body` element in inches. This way, you create a printable area that matches the dimensions of the paper minus the desired margins【8†(source)】.
   ```css
   body {
     width: 7.5in; /* 8.5in - 0.5in padding on either side */
     padding: 0.5in;
   }
   ```
   - Another method is to use a CSS reset template and with "shrink to page" turned off in print options, create a `DIV` that is `7"` wide and `9.5"` high. This approach allows you to position elements inside this box, which translates well between printers. According to the source, the print DPI (Dots Per Inch) is about `95ppi`【9†(source)】.
   ```css
   /* After CSS reset */
   div {
     width: 7in; /* About 670px */
     height: 9.5in; /* About 900px */
   }
   ```

3. **General Approach:**
   - To ensure consistent print size across documents, it's essential that the "logical page" that browsers use for printing is standardized across documents. This logical page is how browsers group elements for printing, and by ensuring a consistent size, you can achieve a consistent print layout across different documents【5†(source)】.

These methods provide a solid foundation for formatting your HTML pages to align with standard paper sizes for printing.
